default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: quotes_admin_dev

test:
  <<: *default
  database: quotes_admin_test

production:
  <<: *default
  database: quotes_admin
